# Generated by Django 3.2.10 on 2021-12-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id_level', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(max_length=3, verbose_name='Уровень доступа')),
                ('discriptions', models.TextField(max_length=100, verbose_name='Наименование доступа')),
                ('create', models.BooleanField(default=False, verbose_name='Создание нового')),
                ('read', models.BooleanField(default=False, verbose_name='Чтение')),
                ('edit', models.BooleanField(default=False, verbose_name='Изменение')),
                ('deletion', models.BooleanField(default=False, verbose_name='Удаление')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_access', models.BooleanField(default=True, verbose_name='Доступ разрешен')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlevel', verbose_name='Уровень доступа')),
            ],
        ),
    ]
