# Generated by Django 3.2.10 on 2021-12-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MallList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_mall', models.IntegerField(max_length=5, verbose_name='Номер магазина')),
                ('city', models.TextField(max_length=100, verbose_name='Город')),
                ('address', models.TextField(max_length=255, verbose_name='Адрес')),
                ('mall', models.TextField(max_length=255, verbose_name='Торговый центр')),
                ('director', models.TextField(max_length=100, verbose_name='Директор')),
                ('business', models.TextField(max_length=100, verbose_name='Бизнес')),
                ('brand', models.TextField(max_length=100, verbose_name='Брэнд')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id_level', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(max_length=3, verbose_name='Уровень доступа')),
                ('discriptions', models.TextField(max_length=100, verbose_name='Наименование доступа')),
                ('create', models.BooleanField(default=False, verbose_name='Создание нового')),
                ('read', models.BooleanField(default=False, verbose_name='Чтение')),
                ('edit', models.BooleanField(default=False, verbose_name='Изменение')),
                ('deletion', models.BooleanField(default=False, verbose_name='Удаление')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_access', models.BooleanField(default=True, verbose_name='Доступ разрешен')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlevel', verbose_name='Уровень доступа')),
            ],
        ),
        migrations.CreateModel(
            name='UserMall',
            fields=[
                ('id_user_mall', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=100, verbose_name='Имя')),
                ('user_surname', models.TextField(max_length=100, verbose_name='Фамилия')),
                ('position', models.TextField(max_length=255, verbose_name='Должность')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlist', verbose_name='ID user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInWork',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('system', models.TextField(max_length=255, verbose_name='Тип системы')),
                ('text_fault', models.TextField(max_length=500, verbose_name='Описание проблемы')),
                ('problem_solution', models.TextField(max_length=500, verbose_name='Решение по проблеме')),
                ('in_work', models.BooleanField(default=False, verbose_name='Заявка в работе')),
                ('done', models.BooleanField(default=False, verbose_name='Заявка выполнена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('id_mall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.malllist', verbose_name='Магазин')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlist', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id_spec', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.TextField(max_length=100, verbose_name='Имя')),
                ('spec_surname', models.TextField(max_length=100, verbose_name='Фамилия')),
                ('position', models.TextField(max_length=255, verbose_name='Должность')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlist', verbose_name='ID user')),
            ],
        ),
        migrations.AddField(
            model_name='malllist',
            name='id_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.specialist', verbose_name='Специалист'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id_contractor', models.AutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.TextField(max_length=255, verbose_name='Наиманование организации')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task_board.userlist', verbose_name='ID user')),
            ],
        ),
    ]
